In [10]:
import pandas as pd 

data = pd.read_csv('../data/public/kdd_finger.gz')
data

0  1    2  label
0     0  7  137      0
1     0  7  140      0
2     0  9  140      0
3     0  7  276      0
4     0  7  173      0
...  .. ..  ...    ...
1028  5  9  222      0
1029  6  8  361      0
1030  4  9  223      0
1031  1  6  221      0
1032  0  8  497      0

[1033 rows x 4 columns]

In [19]:
X = np.array(data)

In [28]:
np.c_[X, np.arange(len(X))]

array([[   0,    7,  137,    0,    0],
       [   0,    7,  140,    0,    1],
       [   0,    9,  140,    0,    2],
       ...,
       [   4,    9,  223,    0, 1030],
       [   1,    6,  221,    0, 1031],
       [   0,    8,  497,    0, 1032]], dtype=int64)

In [29]:
X[0]

array([  0,   7, 137,   0], dtype=int64)

In [18]:
np.arange(len(data))

array([   0,    1,    2, ..., 1030, 1031, 1032])

In [36]:
X[:-1, :-1].shape

(1032, 3)

In [35]:
X[1:, :-1].shape

(1032, 3)

In [12]:
import numpy as np
a = np.arange(3).reshape(1,3)
a.shape

(1, 3)

In [2]:
import numpy as np
a = np.empty((0,3))

In [6]:
print(a[None])

[]
